--PIVIOTING
-- one to one pivioting 

USE tempdb;
IF OBJECT_ID(N'dbo.OpenSchema', N'U') IS NOT NULL DROP TABLE dbo.OpenSchema;
CREATE TABLE dbo.OpenSchema
(
objectid INT NOT NULL,
attribute NVARCHAR(30) NOT NULL,
value SQL_VARIANT NOT NULL,
CONSTRAINT PK_OpenSchema PRIMARY KEY (objectid, attribute)
);
GO
INSERT INTO dbo.OpenSchema(objectid, attribute, value) VALUES
(1, N'attr1', CAST(CAST('ABC' AS VARCHAR(10)) AS SQL_VARIANT)),
(1, N'attr2', CAST(CAST(10 AS INT) AS SQL_VARIANT)),
(1, N'attr3', CAST(CAST('20130101' AS DATE) AS SQL_VARIANT)),
(2, N'attr2', CAST(CAST(12 AS INT) AS SQL_VARIANT)),
(2, N'attr3', CAST(CAST('20150101' AS DATE) AS SQL_VARIANT)),
(2, N'attr4', CAST(CAST('Y' AS CHAR(1)) AS SQL_VARIANT)),
(2, N'attr5', CAST(CAST(13.7 AS NUMERIC(9,3))AS SQL_VARIANT)),
(3, N'attr1', CAST(CAST('XYZ' AS VARCHAR(10)) AS SQL_VARIANT)),
(3, N'attr2', CAST(CAST(20 AS INT) AS SQL_VARIANT)),
(3, N'attr3', CAST(CAST('20140101' AS DATE) AS SQL_VARIANT));

SELECT OBJECTID, attribute, value
FROM DBO.OpenSchema

SELECT OBJECTID, 
MAX(CASE WHEN ATTRIBUTE = 'ATTR1' THEN VALUE END) AS ATTR1,
MAX(CASE WHEN ATTRIBUTE = 'ATTR2' THEN VALUE END) AS ATTR2,
MAX(CASE WHEN attribute = 'attr3' THEN value END) AS attr3,
MAX(CASE WHEN attribute = 'attr4' THEN value END) AS attr4,
MAX(CASE WHEN attribute = 'attr5' THEN value END) AS attr5
FROM DBO.OpenSchema
GROUP BY OBJECTID


SELECT OBJECTID, attribute, value
FROM DBO.OpenSchema

SELECT objectid, ATTR1, ATTR2, ATTR3, ATTR4, ATTR5
FROM DBO.OpenSchema
PIVOT (MAX(VALUE) FOR ATTRIBUTE IN (ATTR1, ATTR2, ATTR3, ATTR4, ATTR5)) AS P;

-- MANY TO ONE PIVOT