--CHAPTER 6 DATA MODIFICATION 

--SELECT INTO

SET NOCOUNT ON;
USE PerformanceV3;
IF OBJECT_ID(N'dbo.MyOrders', N'U') IS NOT NULL DROP TABLE dbo.MyOrders;


SELECT ORDERID, CUSTID, EMPID, SHIPPERID, ORDERDATE, FILLER
INTO DBO.MYORDERS
FROM DBO.ORDERS

select COUNT(*) 
FROM DBO.MYORDERS


select COUNT(*) 
FROM DBO.ORDERS

--pg 476