--CHAPTER-04
--WINDOWS FUNCTION
--AGGREGATED WINDOWS FUNCTION

SET NOCOUNT ON;
USE tempdb;

--ORDERVALUE TABLE
IF OBJECT_ID(N'DBO.ORDERVALUES', N'U') IS NOT NULL DROP TABLE DBO.ORDERVALUES;

SELECT * INTO DBO.ORDERVALUES FROM TSQLV3.Sales.OrderValues

ALTER TABLE DBO.ORDERVALUES ADD CONSTRAINT PK_ORDERVALUES PRIMARY KEY (ORDERID);

GO

--EMPORDERS TABLE

IF OBJECT_ID(N'DBO.EMPORDERS', N'U') IS NOT NULL DROP TABLE DBO.EMPORDERS;

SELECT empid, ISNULL(ordermonth, CAST('19000101' AS DATE)) AS ordermonth, qty,
val, numorders
INTO DBO.EMPORDERS
FROM TSQLV3.Sales.EmpOrders;

ALTER TABLE DBO.EMPORDERS ADD CONTRAINT PK_EMPORDERS PRIMARY KEY(EMPID, ORDERMONTH);
GO

--TRANSATIONS TABLE 

-- PG 343

