--PIVIOTING
-- one to one pivioting 

USE tempdb;
IF OBJECT_ID(N'dbo.OpenSchema', N'U') IS NOT NULL DROP TABLE dbo.OpenSchema;
CREATE TABLE dbo.OpenSchema
(
objectid INT NOT NULL,
attribute NVARCHAR(30) NOT NULL,
value SQL_VARIANT NOT NULL,
CONSTRAINT PK_OpenSchema PRIMARY KEY (objectid, attribute)
);
GO
INSERT INTO dbo.OpenSchema(objectid, attribute, value) VALUES
(1, N'attr1', CAST(CAST('ABC' AS VARCHAR(10)) AS SQL_VARIANT)),
(1, N'attr2', CAST(CAST(10 AS INT) AS SQL_VARIANT)),
(1, N'attr3', CAST(CAST('20130101' AS DATE) AS SQL_VARIANT)),
(2, N'attr2', CAST(CAST(12 AS INT) AS SQL_VARIANT)),
(2, N'attr3', CAST(CAST('20150101' AS DATE) AS SQL_VARIANT)),
(2, N'attr4', CAST(CAST('Y' AS CHAR(1)) AS SQL_VARIANT)),
(2, N'attr5', CAST(CAST(13.7 AS NUMERIC(9,3))AS SQL_VARIANT)),
(3, N'attr1', CAST(CAST('XYZ' AS VARCHAR(10)) AS SQL_VARIANT)),
(3, N'attr2', CAST(CAST(20 AS INT) AS SQL_VARIANT)),
(3, N'attr3', CAST(CAST('20140101' AS DATE) AS SQL_VARIANT));

SELECT OBJECTID, attribute, value
FROM DBO.OpenSchema

SELECT OBJECTID, 
MAX(CASE WHEN ATTRIBUTE = 'ATTR1' THEN VALUE END) AS ATTR1,
MAX(CASE WHEN ATTRIBUTE = 'ATTR2' THEN VALUE END) AS ATTR2,
MAX(CASE WHEN attribute = 'attr3' THEN value END) AS attr3,
MAX(CASE WHEN attribute = 'attr4' THEN value END) AS attr4,
MAX(CASE WHEN attribute = 'attr5' THEN value END) AS attr5
FROM DBO.OpenSchema
GROUP BY OBJECTID


SELECT OBJECTID, attribute, value
FROM DBO.OpenSchema

SELECT objectid, ATTR1, ATTR2, ATTR3, ATTR4, ATTR5
FROM DBO.OpenSchema
PIVOT (MAX(VALUE) FOR ATTRIBUTE IN (ATTR1, ATTR2, ATTR3, ATTR4, ATTR5)) AS P;

-- MANY TO ONE PIVOT

USE TSQLV3

SELECT CUSTID, 
SUM( CASE WHEN ORDERYEAR = 2013 THEN VAL END) AS [2013],
SUM( CASE WHEN ORDERYEAR = 2014 THEN VAL END) AS [2014],
SUM( CASE WHEN ORDERYEAR = 2015 THEN VAL END) AS [2015]
FROM (SELECT CUSTID, YEAR(ORDERDATE) AS ORDERYEAR, VAL FROM 
SALES.ORDERVALUES) AS D
GROUP BY CUSTID;

SELECT CUSTID, [2013], [2014], [2015]
FROM (SELECT CUSTID, YEAR(ORDERDATE) AS ORDERYEAR, VAL FROM SALES.OrderValues) AS D
PIVOT (SUM(VAL) FOR ORDERYEAR IN ([2013], [2014],[2015])) AS P;


IF OBJECT_ID(N'dbo.Matrix', N'U') IS NOT NULL DROP TABLE dbo.Matrix;
CREATE TABLE dbo.Matrix
(
orderyear INT NOT NULL PRIMARY KEY,
y2013 INT NULL,
y2014 INT NULL,
y2015 INT NULL
);
GO
INSERT INTO dbo.Matrix(orderyear, y2013) VALUES(2013, 1);
INSERT INTO dbo.Matrix(orderyear, y2014) VALUES(2014, 1);
INSERT INTO dbo.Matrix(orderyear, y2015) VALUES(2015, 1);
SELECT orderyear, y2013, y2014, y2015 FROM dbo.Matrix;

--PG396
USE TSQLV3

SELECT 
CUSTID, 
SUM(VAL*Y2013) AS [2013], 
SUM(VAL*Y2014) AS [2014], 
SUM(VAL*Y2015) AS [2015]
FROM (SELECT CUSTID, YEAR(ORDERDATE) AS ORDERYEAR, VAL FROM SALES.OrderValues) AS D
INNER JOIN DBO.Matrix AS m ON D.ORDERYEAR = M.orderyear
GROUP BY custid

SELECT custid,
SUM(CASE WHEN orderyear = 2013 THEN 1 END) AS [2013],
SUM(CASE WHEN orderyear = 2014 THEN 1 END) AS [2014],
SUM(CASE WHEN orderyear = 2015 THEN 1 END) AS [2015]
FROM (SELECT custid, YEAR(orderdate) AS orderyear
FROM Sales.Orders) AS D
GROUP BY custid;

SELECT custid,
SUM(val*y2013) AS sum2013,
SUM(val*y2014) AS sum2014,
SUM(val*y2015) AS sum2015,
AVG(val*y2013) AS avg2013,
AVG(val*y2014) AS avg2014,
AVG(val*y2015) AS avg2015,
SUM(y2013) AS cnt2013,
SUM(y2014) AS cnt2014,
SUM(y2015) AS cnt2015
FROM (SELECT custid, YEAR(orderdate) AS orderyear, val
FROM Sales.OrderValues) AS D
INNER JOIN dbo.Matrix AS M ON D.orderyear = M.orderyear
GROUP BY custid;

IF OBJECT_ID(N'dbo.PvtOrders', N'U') IS NOT NULL DROP TABLE dbo.PvtOrders



SELECT custid, [2013], [2014], [2015]
INTO dbo.PvtOrders
FROM (SELECT custid, YEAR(orderdate) AS orderyear, val
FROM Sales.OrderValues) AS D
PIVOT(SUM(val) FOR orderyear IN([2013],[2014],[2015])) AS P;

SELECT custid, [2013], [2014], [2015] FROM dbo.PvtOrders;

--PG 400