USE tempdb

IF OBJECT_ID(N'DBO.T1',N'U') IS NOT NULL DROP TABLE DBO.T1;

CREATE TABLE DBO.T1
(
COL1 INT NOT NULL IDENTITY, 
COL2 VARCHAR(100) NOT NULL, 
FILLER BINARY(2000) NULL DEFAULT(0X), 
CONSTRAINT PK_T1 PRIMARY KEY(COL1)
)

INSERT INTO DBO.T1(COL2) SELECT 'STRING '+ CAST(N AS VARCHAR(10))
FROM TSQLV3.DBO.GetNums(1,100) AS NUMS;

DECLARE @S AS VARCHAR(MAX);
SET @S = '';

SELECT @S = @S+COL2 + ';'
FROM DBO.T1
ORDER BY COL1;

PRINT @S

CREATE NONCLUSTERED INDEX IDX_NC_COL2_I_COL1 ON DBO.T1 (COL2, COL1);
GO

DECLARE @S AS VARCHAR(MAX);
SET @S = '';

SELECT @S = @S+COL2 + ';'
FROM DBO.T1
ORDER BY COL1;

PRINT @S

-- AGGREDATE PRODUCT

SELECT GROUPID, ROUND(EXP(SUM(LOG(VAL))),0) AS PRODUCT
FROM DBO.Groups
GROUP BY GROUPID;

--PG 416