-- The UNION, EXCEPT, and INTERSECT operators PG332
--UNION AND UNION ALL

--SELECT 
--COUNTRY, REGION, CITY 
--FROM HR.Employees

--UNION

--SELECT COUNTRY, REGION, CITY
--FROM Sales.Customers



--SELECT 
--COUNTRY, REGION, CITY 
--FROM HR.Employees

--UNION ALL

--SELECT COUNTRY, REGION, CITY
--FROM Sales.Customers

--USE tempdb

--IF OBJECT_ID(N'DBO.T2014',  N'U') IS NOT NULL DROP TABLE DBO.T2014
--IF OBJECT_ID(N'DBO.T2015',  N'U') IS NOT NULL DROP TABLE DBO.T2015

--GO 

--CREATE TABLE DBO.T2014 (
--KEYCOL INT NOT NULL CONSTRAINT PK_T2014 PRIMARY KEY, 
--DT DATE NOT NULL CONSTRAINT CHK_T2014 CHECK(DT > = '20140101' AND DT < '20150101')
--)

--CREATE TABLE DBO.T2015 (
--KEYCOL INT NOT NULL CONSTRAINT PK_T2015 PRIMARY KEY, 
--DT DATE NOT NULL CONSTRAINT CHK_T2015 CHECK(DT > = '20150101' AND DT < '20160101')
--);

--SELECT keycol, dt FROM dbo.T2014
--UNION
--SELECT keycol, dt FROM dbo.T2015;


----INTERSECT COMMON ROWS 

--USE TSQLV3
--SELECT 
--COUNTRY, REGION, CITY 
--FROM HR.Employees

--INTERSECT

--SELECT COUNTRY, REGION, CITY
--FROM Sales.Customers



WITH INTERSECT_ALL
AS
(
SELECT ROW_NUMBER() OVER(PARTITION BY COUNTRY, REGION, CITY ORDER BY (SELECT 0))  AS RN,
COUNTRY, REGION, CITY
FROM Sales.Customers

INTERSECT 

SELECT ROW_NUMBER() OVER(PARTITION BY COUNTRY, REGION, CITY ORDER BY (SELECT 0))  AS RN,
COUNTRY, REGION, CITY
FROM HR.Employees

)


SELECT COUNTRY, REGION, CITY FROM INTERSECT_ALL

--EXCEPT OPERATOR

PG 339