-- CHAPTER 7 WORKING WITH DATE AND TIME. 

--DATETIME; SMALLDATETIME; DATE; TIME; DATETIME; DATETIMEOFFSET
USE tempdb
SELECT SYSDATETIMEOFFSET();


--DATE AND TIME FUNCTION

SELECT
CAST(SYSDATETIMEOFFSET() AS date) AS "date"
, CAST(SYSDATETIMEOFFSET() AS TIME) AS TIME


SELECT
DATEPART(month, SYSDATETIMEOFFSET()) AS monthnum,
DATEPART(weekday, SYSDATETIMEOFFSET()) AS weekdaynum; --PG 533