--CHAPTER 3

USE TSQLV3;

--SELECT Custid,COUNT(DISTINCT empid)
--FROM Sales.Orders
--group by custid
--having COUNT(DISTINCT empid) = (Select count(*) from hr.Employees)


--SELECT *
--FROM Sales.Orders
--WHERE orderdate IN 
--(
--SELECT  MAX(orderdate) AS LASTDATE
--FROM Sales.Orders
--GROUP BY YEAR(orderdate), MONTH(ORDERDATE))


--CORRELATED QUERIES

--SELECT *
--FROM Sales.ORDERS O1
--WHERE O1.orderdate =

--(SELECT MAX(ORDERDATE)
--FROM Sales.Orders O2

--WHERE O2.CUSTID = O1.CUSTID)
--ORDER BY CUSTID

--PG -261

--SELECT orderid, orderdate, custid, empid
--FROM Sales.Orders AS O1
--WHERE orderdate =
--(SELECT MAX(orderdate)
--FROM Sales.Orders AS O2
--WHERE O2.custid = O1.custid)
--AND orderid =
--(SELECT MAX(orderid)
--FROM Sales.Orders AS O2
--WHERE O2.custid = O1.custid
----AND O2.orderdate = O1.orderdate);

--SELECT orderid, orderdate, custid, empid
--FROM Sales.Orders AS O1
--WHERE orderid =
--(SELECT TOP (1) orderid
--FROM Sales.Orders AS O2
--WHERE O2.custid = O1.custid
--ORDER BY orderdate DESC, orderid DESC);


--CREATE UNIQUE INDEX IDX_POC 
--ON 
--SALES.ORDERS(CUSTID, ORDERDATE DESC, ORDERID DESC) INCLUDE(EMPID);

--SELECT
--(SELECT TOP (1) orderid
--FROM Sales.Orders AS O
--WHERE O.custid = C.custid
--ORDER BY orderdate DESC, orderid DESC) AS orderid
--FROM Sales.Customers AS C;


--SELECT orderid, orderdate, custid, empid
--FROM Sales.Orders
--WHERE orderid IN 
--(
--SELECT 
--(SELECT TOP (1) orderid
--FROM SALES.Orders AS O
--WHERE O.custid = c.CUSTID
--ORDER BY orderdate DESC, orderid DESC) AS ORDERID

--FROM Sales.Customers AS C)


--DROP INDEX idx_poc ON Sales.Orders;


-- THE EXIST PREDICATE

--SELECT  custid, companyname
--FROM SALES.CUSTOMERS AS C
--WHERE EXISTS 
--(SELECT * 
--FROM Sales.Orders AS O
--WHERE O.custid = C.custid)


--SET NOCOUNT ON;
--USE tempdb;
--IF OBJECT_ID(N'DBO.T1' , N'U') IS NOT NULL DROP TABLE DBO.T1;
--CREATE TABLE T1( COL1 INT NOT NULL CONSTRAINT PF_T1 PRIMARY KEY);
--INSERT INTO DBO.T1 VALUES(1),(2), (3),(7),(8),(9),(11),(15),(16),(17),(28);

--TRUNCATE TABLE dbo.T1;
--INSERT INTO dbo.T1 WITH (TABLOCK) (col1)
--SELECT n FROM TSQLV3.dbo.GetNums(1, 10000000) AS Nums WHERE n % 10000 <> 0
--OPTION(MAXDOP 1);

--SELECT MIN(A.COL1) + 1 AS MISSINGVAL
--FROM DBO.T1 AS A
--WHERE NOT EXISTS(
--SELECT * FROM dbo.T1 AS B
--WHERE A.COL1 = B.COL1 +1) ;


--SELECT TOP (1) A.col1 + 1 AS missingval
--FROM dbo.T1 AS A
--WHERE NOT EXISTS
--(SELECT *
--FROM dbo.T1 AS B
--WHERE B.col1 = A.col1 + 1)
--ORDER BY A.col1 + 1;

--SELECT TOP (1) A.col1 + 1 AS missingval
--FROM dbo.T1 AS A
--WHERE NOT EXISTS
--(SELECT *
--FROM dbo.T1 AS B
--WHERE A.col1 = B.col1 - 1)
--ORDER BY A.col1;



----CASE STATEMENT TO FIND MISSING

--SELECT 
--CASE
--WHEN NOT EXISTS ( SELECT * FROM DBO.T1 WHERE COL1 = 1) THEN 1
--ELSE (SELECT TOP(1) A.COL1+1 AS MISSINGVAL FROM DBO.T1 AS A  WHERE NOT EXISTS (SELECT * FROM DBO.T1 AS B
--WHERE B.COL1 = A.COL1 -1) ORDER BY MISSINGVAL)
--END AS MISSINGVAL

--SELECT col1
--FROM dbo.T1 AS A
--SELECT col1
--FROM dbo.T1 AS A
--WHERE NOT EXISTS
--(SELECT *
--FROM dbo.T1 AS B
--WHERE B.col1 = A.col1 + 1)
--AND col1 < (SELECT MAX(col1) FROM dbo.T1);


--SELECT COL1+1 AS RANGE_FROM, 
--	(SELECT MIN(B.COL1)
--	FROM DBO.T1 AS B
--	WHERE B.COL1 >A.COL1) -1 AS RANGE_TO
--FROM DBO.T1 AS A
--WHERE NOT EXISTS (
--SELECT * FROM DBO.T1 AS B
--WHERE B.COL1 = a.COL1+1) AND
--COL1< (SELECT MAX(COL1) FROM DBO.T1);



--use TSQLV3

--SELECT custid
--FROM Sales.Orders
--GROUP BY CUSTID 
--HAVING COUNT(DISTINCT EMPID) = (SELECT COUNT(*) FROM HR.Employees);




--SELECT CUSTID, COMPANYNAME
--FROM Sales.Customers AS C
--WHERE NOT EXISTS(
--SELECT * FROM HR.Employees as E
--WHERE NOT EXISTS (
--SELECT * FROM Sales.Orders AS O
--WHERE O.custid = C.custid AND 
--O.empid = E.empid));


--IF OBJECT_ID(N'dbo.T1', N'U') IS NOT NULL DROP TABLE dbo.T1;
--IF OBJECT_ID(N'dbo.T2', N'U') IS NOT NULL DROP TABLE dbo.T2;
--GO
--CREATE TABLE dbo.T1(col1 INT NOT NULL);
--CREATE TABLE dbo.T2(col2 INT NOT NULL);
--INSERT INTO dbo.T1(col1) VALUES(1);
--INSERT INTO dbo.T1(col1) VALUES(2);
--INSERT INTO dbo.T1(col1) VALUES(3);
--INSERT INTO dbo.T2(col2) VALUES(2);

-- SUBQUERY WHEN COLUMNS NAME  CAN BE SAME  - MISTAKE 

--SELECT * FROM DBO.T1
--SELECT * FROM DBO.T2

--SELECT COL1
--FROM DBO.T1 WHERE COL1 IN ( SELECT T2.COL2 FROM DBO.T2)




--IF OBJECT_ID(N'dbo.T1', N'U') IS NOT NULL DROP TABLE dbo.T1;
--IF OBJECT_ID(N'dbo.T2', N'U') IS NOT NULL DROP TABLE dbo.T2;
--GO
--CREATE TABLE dbo.T1(col1 INT NULL);
--CREATE TABLE dbo.T2(col1 INT NOT NULL);
--INSERT INTO dbo.T1(col1) VALUES(1);
--INSERT INTO dbo.T1(col1) VALUES(2);
--INSERT INTO dbo.T1(col1) VALUES(NULL);
--INSERT INTO dbo.T2(col1) VALUES(2);
--INSERT INTO dbo.T2(col1) VALUES(3);


-- VLAUE APPEAR IN T2 NOT IN T1

--SELECT T2.col1
--FROM DBO.T2 
--WHERE T2.col1 NOT IN (SELECT T1.col1 FROM DBO.T1 WHERE T1.col1 IS NOT NULL)

--SELECT T2.col1
--FROM DBO.T2 
--WHERE NOT EXISTS (SELECT T1.col1 FROM DBO.T1 WHERE T1.col1 = T2.col1)

-- DERIVED TABLE




--IF OBJECT_ID(N'dbo.T1', N'U') IS NOT NULL DROP TABLE dbo.T1;
--GO
--CREATE TABLE dbo.T1(col1 INT);
--INSERT INTO dbo.T1(col1) VALUES(1);
--INSERT INTO dbo.T1(col1) VALUES(2);


--SELECT COL1, EXPR+1 AS EXPR2
--FROM (
--SELECT T1.col1, T1.col1 + 1 AS EXPR
--FROM T1) AS D;


--SELECT ORDERYEAR, NUMCUSTS
--FROM 

--( SELECT ORDERYEAR, COUNT( DISTINCT CUSTID) AS NUMCUSTS FROM 


--(SELECT YEAR(ORDERDATE) AS ORDERYEAR, CUSTID FROM Sales.Orders)  AS d1


--GROUP BY ORDERYEAR) AS D2
--WHERE NUMCUSTS > 70


--SELECT CUR.orderyear, CUR.numorders, PRV.numorders, CUR.numorders - PRV.numorders AS diff
--FROM (SELECT YEAR(orderdate) AS orderyear, COUNT(*) AS numorders
--FROM Sales.Orders
--GROUP BY YEAR(orderdate)) AS CUR
--LEFT OUTER JOIN
--(SELECT YEAR(orderdate) AS orderyear, COUNT(*) AS numorders
--FROM Sales.Orders
--GROUP BY YEAR(orderdate)) AS PRV
--ON CUR.orderyear = PRV.orderyear + 1;

--PG 282 CTEs

-- CTE

--WITH ORDERCOUNT 
--AS 
--(SELECT YEAR(orderdate) AS ORDERYEAR, COUNT(*) AS NUMORDERS
--FROM Sales.Orders
--GROUP BY YEAR(orderdate))

--SELECT ORDERYEAR , NUMORDERS
--FROM ORDERCOUNT

--WITH C1 AS 
--(
--SELECT YEAR(ORDERDATE) AS ORDERYEAR, CUSTID FROM SALES.ORDERS),
--C2 AS 
--(
--SELECT ORDERYEAR, COUNT(DISTINCT CUSTID) AS NUMCUSTS
--FROM C1 GROUP BY ORDERYEAR)

--SELECT ORDERYEAR, NUMCUSTS
--FROM C2
--WHERE NUMCUSTS > 70;


--WITH ORDERCOUNT
--AS
--(
--SELECT 
--	YEAR(ORDERDATE) AS ORDERYEAR, COUNT(*) AS NUMORDERS
--FROM Sales.Orders
--GROUP BY YEAR(ORDERDATE)
--)

--SELECT CUR.ORDERYEAR, CUR.NUMORDERS, PRV.NUMORDERS, CUR.NUMORDERS - PRV.NUMORDERS AS DIFF
--FROM ORDERCOUNT AS CUR
--LEFT OUTER JOIN ORDERCOUNT AS PRV 
--ON CUR.ORDERYEAR = PRV.ORDERYEAR +1


-- PG 284

--SET NOCOUNT ON;
--USE tempdb;
--IF OBJECT_ID(N'dbo.Employees', N'U') IS NOT NULL DROP TABLE dbo.Employees;
--CREATE TABLE dbo.Employees
--(
--empid INT NOT NULL
--CONSTRAINT PK_Employees PRIMARY KEY,
--mgrid INT NULL
--CONSTRAINT FK_Employees_Employees FOREIGN KEY REFERENCES
--dbo.Employees(empid),
--empname VARCHAR(25) NOT NULL,
--salary MONEY NOT NULL
--);
--INSERT INTO dbo.Employees(empid, mgrid, empname, salary)
--VALUES(1, NULL, 'David' , $10000.00),
--(2, 1, 'Eitan' , $7000.00),
--(3, 1, 'Ina' , $7500.00),
--(4, 2, 'Seraph' , $5000.00),
--(5, 2, 'Jiru' , $5500.00),
--(6, 2, 'Steve' , $4500.00),
--(7, 3, 'Aaron' , $5000.00),
--(8, 5, 'Lilach' , $3500.00),
--(9, 7, 'Rita' , $3000.00),
--(10, 5, 'Sean' , $3000.00),
--(11, 7, 'Gabriel', $3000.00),
--(12, 9, 'Emilia' , $2000.00),
--(13, 9, 'Michael', $2000.00),
--(14, 9, 'Didi' , $1500.00);
--CREATE UNIQUE INDEX idx_nc_mgr_emp_i_name_sal
--ON dbo.Employees(mgrid, empid) INCLUDE(empname, salary);




--SELECT * FROM DBO.EMPLOYEES







--WITH  EMPSCTE AS 
--(
--SELECT EMPID, MGRID, EMPNAME, SALARY
--FROM dbo.Employees
--WHERE EMPID = 3

--UNION ALL

--SELECT C.EMPID, C.MGRID, C.EMPNAME, C.SALARY
--FROM EMPSCTE AS P JOIN
--DBO.EMPLOYEES AS C
--ON C.MGRID = P.EMPID
--)

--SELECT EMPID, MGRID, EMPNAME, SALARY FROM EMPSCTE;

-- VIEWS


--USE TSQLV3;
--IF OBJECT_ID(N'SALES.USACUSTS',N'V') IS NOT NULL DROP VIEW SALES.USACUSTS;
--GO

--CREATE VIEW SALES.USACUTS WITH SCHEMABINDING
--AS 

--SELECT
--custid, companyname, contactname, contacttitle, address, CITY, REGION, postalcode, COUNTRY, phone, FAX


--FROM Sales.Customers
--WHERE country = N'USA'
--WITH CHECK OPTION;


--SELECT custid, companyname
--FROM Sales.Customers
--WHERE COUNTRY = N'USA'
--ORDER BY REGION, CITY;

